a=str(input('Digite uma profissão: '))

print('O tipo primitivo desse valor é :', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Esta em maiúsculas? ', a.isupper())
print('Esta em minúsculas? ', a.islower())
print('Esta capitalizada? ', a.capitalize())
